scrape_configs:
  - job_name: "starlink"
    static_configs:
      - targets: ["%s"]

    # this allows us to use the dish-id as a target, but still poll localhost
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: %s
