version: "3.9"
services:
  starlink-exporter:
    build:
            dockerfile: cmd/starlink-exporter/Dockerfile 
            context: ../../
    ports:
            - "2112:2112"
    environment:
            REMOTE: "http://prometheus:9090/api/v1/write"
  prometheus:
    image: "quay.io/prometheus/prometheus:v2.25.0"
    ports:
            - "9090:9090"
    volumes:
            - ../prometheus/dev.yml:/etc/prometheus/prometheus.yml
    entrypoint: ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--enable-feature=remote-write-receiver"]
  grafana:
    image: "grafana/grafana"
    ports:
            - "3000:3000"
    volumes:
            - ../grafana/provisioning/:/etc/grafana/provisioning/
